### ISSUE TITLE
error while uploading the plugin to the server

### ISSUE THREAD

**Issue by Toxic2131** [MagmaGuy/BetterStructures#14]
I have this error when uploading the plugin to the server and unfortunately I don't know how to deal with it.
Server: 3553-Spigot-14a2382-ef09464 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)

[18:55:18] [Server thread/INFO]: [BetterStructures] Enabling BetterStructures v1.4.0
[18:55:18] [Server thread/INFO]: [BetterStructures] Initialized!
[18:55:18] [Server thread/ERROR]: Error occurred while enabling BetterStructures v1.4.0 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
    at com.magmaguy.betterstructures.configurationimporter.Import.importPackages(Import.java:51) ~[?:?]
    at com.magmaguy.betterstructures.configurationimporter.Import.initialize(Import.java:46) ~[?:?]
    at com.magmaguy.betterstructures.BetterStructures.onEnable(BetterStructures.java:31) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:523) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
    at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:437) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
    at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
    at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
