### ISSUE TITLE
not compatible with RealisticSurvival?

### ISSUE THREAD

**Issue by ProjectSky** [MagmaGuy/BetterStructures#15]
not sure if RealisticSurvival or BetterStructures is causing this issues

```
[21:54:49] [Server thread/INFO]: [BetterStructures] Enabling BetterStructures v1.4.2
[21:54:49] [Server thread/INFO]: [BetterStructures] Initialized!
[21:54:49] [Server thread/ERROR]: Error occurred while enabling BetterStructures v1.4.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.mojang.datafixers.types.Type.everywhere(com.mojang.datafixers.TypeRewriteRule, com.mojang.datafixers.functions.PointFreeRule, boolean, boolean)" because "type" is null
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.TaggedChoice$TaggedChoiceType.lambda$all$1(TaggedChoice.java:136) ~[datafixerupper-5.0.28.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.mojang.datafixers.types.templates.TaggedChoice$TaggedChoiceType.all(TaggedChoice.java:139) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Named$NamedType.all(Named.java:112) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Check$CheckType.all(Check.java:150) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Check$CheckType.everywhere(Check.java:158) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:168) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:168) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:168) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:168) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:168) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.families.RecursiveTypeFamily.everywhere(RecursiveTypeFamily.java:151) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.RecursivePoint$RecursivePointType.everywhere(RecursivePoint.java:172) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.List$ListType.all(List.java:120) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Tag$TagType.all(Tag.java:144) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:168) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Product$ProductType.all(Product.java:169) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.TaggedChoice$TaggedChoiceType.lambda$all$1(TaggedChoice.java:136) ~[datafixerupper-5.0.28.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.mojang.datafixers.types.templates.TaggedChoice$TaggedChoiceType.all(TaggedChoice.java:139) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.templates.Named$NamedType.all(Named.java:112) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:195) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.everywhere(Type.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:295) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:87) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:77) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.rewrite(Type.java:190) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.readAndWrite(Type.java:152) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:84) ~[datafixerupper-5.0.28.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.ext.fawe.v1_19_R2.PaperweightDataConverters$WrappedDataFixer.update(PaperweightDataConverters.java:247) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.ext.fawe.v1_19_R2.PaperweightDataConverters.convert(PaperweightDataConverters.java:302) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.ext.fawe.v1_19_R2.PaperweightDataConverters.convert(PaperweightDataConverters.java:295) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.ext.fawe.v1_19_R2.PaperweightDataConverters.convert(PaperweightDataConverters.java:282) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.ext.fawe.v1_19_R2.PaperweightDataConverters.fixBlockEntity(PaperweightDataConverters.java:109) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.sk89q.worldedit.bukkit.adapter.ext.fawe.v1_19_R2.PaperweightDataConverters.fixUp(PaperweightDataConverters.java:88) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReader.fixBlockEntity(FastSchematicReader.java:113) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReader.read(FastSchematicReader.java:366) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:47) ~[FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346.jar:?]
	at com.magmaguy.betterstructures.worldedit.Schematic.load(Schematic.java:37) ~[BetterStructures.jar:?]
	at com.magmaguy.betterstructures.config.schematics.SchematicConfig.scanDirectoryForSchematics(SchematicConfig.java:62) ~[BetterStructures.jar:?]
	at com.magmaguy.betterstructures.config.schematics.SchematicConfig.scanDirectoryForSchematics(SchematicConfig.java:65) ~[BetterStructures.jar:?]
	at com.magmaguy.betterstructures.config.schematics.SchematicConfig.<init>(SchematicConfig.java:30) ~[BetterStructures.jar:?]
	at com.magmaguy.betterstructures.BetterStructures.onEnable(BetterStructures.java:42) ~[BetterStructures.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:630) ~[purpur-1.19.3.jar:git-Purpur-1908]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544) ~[purpur-1.19.3.jar:git-Purpur-1908]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1908]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1908]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1908]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1908]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1908]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:54:49] [Server thread/INFO]: [BetterStructures] Disabling BetterStructures v1.4.2
[21:54:49] [Server thread/INFO]: [BetterStructures] Shutdown!
```

**Comment by MagmaGuy** [comment]
Are you using Asyncworldedit?

**Comment by ProjectSky** [comment]
> Are you using Asyncworldedit?

yes, I'm using FastAsyncWorldEdit-Bukkit-2.5.2-SNAPSHOT-346

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
