### ISSUE TITLE
An error occurred while importing

### ISSUE THREAD

**Issue by 2776901795** [MagmaGuy/BetterStructures#34]
> BetterStructures reload
[16:39:50 INFO]: [BetterStructures] Shutdown!
[16:39:50 INFO]: [BetterStructures] WorldGuard is not enabled! WorldGuard is recommended when using the EliteMobs integration.
[16:39:50 INFO]: [BetterStructures]     ____       __  __            _____ __                  __
[16:39:50 INFO]: [BetterStructures]    / __ )___  / /_/ /____  _____/ ___// /________  _______/ /___  __________  _____
[16:39:50 INFO]: [BetterStructures]   / __  / _ \/ __/ __/ _ \/ ___/\__ \/ __/ ___/ / / / ___/ __/ / / / ___/ _ \/ ___/
[16:39:50 INFO]: [BetterStructures]  / /_/ /  __/ /_/ /_/  __/ /   ___/ / /_/ /  / /_/ / /__/ /_/ /_/ / /  /  __(__  )
java.lang.NullPointerException: Cannot read the array length because "<local6>" is null>
        at [地牢]BetterStructures (1).jar//com.magmaguy.betterstructures.configurationimporter.Import.importPackages(Import.java:63)
        t [地牢]BetterStructures (1).jar//com.magmaguy.betterstructures.configurationimporter.Import.initialize(Import.java:46)K
[16:39:50 INFO]: [BetterStructures] /_____/\___/\__/\__/\___/_/   /____/\__/_/   \__,_/\___/\__/\__,_/_/   \___/____/
        at [地牢]BetterStructures (1).jar//com.magmaguy.betterstructures.BetterStructures.onEnable(BetterStructures.java:44)>
        at [地牢]BetterStructures (1).jar//com.magmaguy.betterstructures.commands.CommandHandler.lambda$constructCommands$6(CommandHandler.java:135)
        t [地牢]BetterStructures (1).jar//com.magmaguy.shaded.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121)
[       at [地牢]BetterStructures (1).jar//com.magmaguy.shaded.cloud.CommandManager.executeCommand(CommandManager.java:176)
K       at [地牢]BetterStructures (1).jar//com.magmaguy.shaded.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:107)[16:39:50 INFO]: [BetterStructures] Initialized version 1.6.2!

>       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
        t org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
[       at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:972)
K       at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:500)
[16:39:50 WARN]: [BetterStructures] Failed to move files from betterstructures_echoes_barn_barren.schem ! Tell the dev!
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)>
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
[16:39:50 WARN]: [BetterStructures] Failed to move files from betterstructures_echoes_barn_barren.yml ! Tell the dev!
        at [地牢]BetterStructures (1).jar//com.magmaguy.betterstructures.configurationimporter.Import.importPackages(Import.java:63)>
        at [地牢]BetterStructures (1).jar//com.magmaguy.betterstructures.configurationimporter.Import.initialize(Import.java:46)
        at [地牢]BetterStructures (1).jar//com.magmaguy.betterstructures.BetterStructures.onEnable(BetterStructures.java:44)
        at [地牢]BetterStructures (1).jar//com.magmaguy.betterstructures.commands.CommandHandler.lambda$constructCommands$6(CommandHandler.java:135)
        at [地牢]BetterStructures (1).jar//com.magmaguy.shaded.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121)
        at [地牢]BetterStructures (1).jar//com.magmaguy.shaded.cloud.CommandManager.executeCommand(CommandManager.java:176)
        at [地牢]BetterStructures (1).jar//com.magmaguy.shaded.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:107)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:972)
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:500)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot read the array length because "<local6>" is null

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
