### ISSUE TITLE
[ BUG / Missing Feature ] Failed to move directories for default!

### ISSUE THREAD

**Issue by SirDank** [MagmaGuy/BetterStructures#39]
How to replicate:
- Paste zips in the `imports` directory before first server boot

What would a simple fix look like:
- Create folders before moving / extracting

Notes:
- This issue does not exist on EliteMobs

Log:
```
[10:45:55 WARN]: [BetterStructures] Failed to move directories for default! Tell the dev!
[10:45:55 WARN]: java.nio.file.NoSuchFileException: C:\Users\SirDank\Desktop\dank.mc\plugins\BetterStructures\imports\BetterStructures Default Pack\schematics\default -> C:\Users\SirDank\Desktop\dank.mc\plugins\BetterStructures\schematics\default
[10:45:55 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[10:45:55 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[10:45:55 WARN]:        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
[10:45:55 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
[10:45:55 WARN]:        at java.base/java.nio.file.Files.move(Files.java:1432)
[10:45:55 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.configurationimporter.Import.moveFile(Import.java:133)
[10:45:55 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.configurationimporter.Import.moveDirectory(Import.java:119)
[10:45:55 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.configurationimporter.Import.importPackages(Import.java:66)
[10:45:55 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.configurationimporter.Import.initialize(Import.java:46)
[10:45:55 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.BetterStructures.onEnable(BetterStructures.java:44)
[10:45:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[10:45:55 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[10:45:55 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:45:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:45:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653)
[10:45:55 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564)
[10:45:55 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[10:45:55 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[10:45:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:346)
[10:45:55 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
[10:45:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[10:45:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
