### ISSUE TITLE
 Failed to correctly fill chests!

### ISSUE THREAD

**Issue by EinNiki** [MagmaGuy/BetterStructures#44]
### Hi is there a fix? Use 1.21 Paper, and Worldedit.

[13:22:42 WARN]: [BetterStructures] Failed to correctly fill chests!
[13:22:42 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.magmaguy.betterstructures.util.WeighedProbability.pickWeighedProbability(java.util.Map)" is null
[13:22:42 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.chests.ChestContents.rollChestContents(ChestContents.java:159)
[13:22:42 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitAnything.fillChests(FitAnything.java:290)
[13:22:42 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitAnything.paste(FitAnything.java:199)
[13:22:42 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitUndergroundBuilding.scan(FitUndergroundBuilding.java:236)
[13:22:42 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitUndergroundBuilding.<init>(FitUndergroundBuilding.java:36)
[13:22:42 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.util.FitUndergroundDeepBuilding.fit(FitUndergroundDeepBuilding.java:17)
[13:22:42 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.listeners.NewChunkLoadEvent.deepUndergroundScanner(NewChunkLoadEvent.java:73)
[13:22:42 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.listeners.NewChunkLoadEvent.onChunkLoad(NewChunkLoadEvent.java:47)
[13:22:42 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor34.execute(Unknown Source)
[13:22:42 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[13:22:42 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:22:42 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:22:42 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:22:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[13:22:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[13:22:42 WARN]:        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:660)
[13:22:42 WARN]:        at ca.spottedleaf.moonrise.common.util.ChunkSystem.onChunkBorder(ChunkSystem.java:91)
[13:22:42 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1296)
[13:22:42 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1364)
[13:22:42 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1348)
[13:22:42 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1303)
[13:22:42 WARN]:        at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:341)
[13:22:42 WARN]:        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:743)
[13:22:42 WARN]:        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337)
[13:22:42 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1525)
[13:22:42 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[13:22:42 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[13:22:42 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
[13:22:42 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473)
[13:22:42 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318)
[13:22:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[13:22:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
