### ISSUE TITLE
java.lang.IllegalArgumentException: BAMBOO_SAPLING isn't an item

### ISSUE THREAD

**Issue by aikomastboom** [MagmaGuy/BetterStructures#46]
plugin version `1.7.1`
server startup:

```log
Starting org.bukkit.craftbukkit.Main
WARN StatusConsoleListener Advanced terminal features are not available in this environment
[bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS; Eclipse Adoptium Temurin-21.0.4+7) on Linux 6.10.3-200.fc40.x86_64 (amd64)
[bootstrap] Loading Paper 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) for Minecraft 1.21
m
...
[BetterStructures] Enabling BetterStructures v1.7.1
```

how I fixed it locally:

```diff
Index: src/main/java/com/magmaguy/betterstructures/chests/ChestContents.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/com/magmaguy/betterstructures/chests/ChestContents.java b/src/main/java/com/magmaguy/betterstructures/chests/ChestContents.java
--- a/src/main/java/com/magmaguy/betterstructures/chests/ChestContents.java	(revision 2d483c0a453b1c1fab41c46ba69a8068a878d690)
+++ b/src/main/java/com/magmaguy/betterstructures/chests/ChestContents.java	(date 1723657423954)
@@ -140,8 +140,13 @@
                 }
             }
             if (material != null || itemStack != null) {
-                ChestEntry chestEntry = new ChestEntry(material, weight, minAmount, maxAmount, itemStack, procedurallyGeneratedEnchantments, treasureConfigFields);
-                chestEntries.add(chestEntry);
+                if(material.isItem()) {
+                    ChestEntry chestEntry = new ChestEntry(material, weight, minAmount, maxAmount, itemStack, procedurallyGeneratedEnchantments, treasureConfigFields);
+                    chestEntries.add(chestEntry);
+                } else {
+                    Logger.warn(material + " is not an Item!");
+                }
+
             }
         }
         return chestEntries;
```

```stacktrace
[BetterStructures] Failed to correctly fill chests!
java.lang.IllegalArgumentException: BAMBOO_SAPLING isn't an item
      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
      at org.bukkit.inventory.ItemStack.of(ItemStack.java:58)
      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138)
      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117)
      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104)
      at 103241.jar//com.magmaguy.betterstructures.chests.ChestEntry.rollEntry(ChestEntry.java:37)
      at 103241.jar//com.magmaguy.betterstructures.chests.ChestContents$ChestRarity.rollLoot(ChestContents.java:187)
      at 103241.jar//com.magmaguy.betterstructures.chests.ChestContents.rollChestContents(ChestContents.java:159)
      at 103241.jar//com.magmaguy.betterstructures.buildingfitter.FitAnything.fillChests(FitAnything.java:290)
      at 103241.jar//com.magmaguy.betterstructures.buildingfitter.FitAnything.paste(FitAnything.java:199)
      at 103241.jar//com.magmaguy.betterstructures.buildingfitter.FitSurfaceBuilding.scan(FitSurfaceBuilding.java:62)
      at 103241.jar//com.magmaguy.betterstructures.buildingfitter.FitSurfaceBuilding.<init>(FitSurfaceBuilding.java:25)
      at 103241.jar//com.magmaguy.betterstructures.listeners.NewChunkLoadEvent.surfaceScanner(NewChunkLoadEvent.java:57)
      at 103241.jar//com.magmaguy.betterstructures.listeners.NewChunkLoadEvent.onChunkLoad(NewChunkLoadEvent.java:45)
      at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source)

```

**Comment by servicomcr** [comment]
[17:53:56 WARN]: [BetterStructures] Failed to correctly fill chests!
[17:53:56 WARN]: java.lang.IllegalArgumentException: BAMBOO_SAPLING isn't an item
[17:53:56 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[17:53:56 WARN]:        at org.bukkit.inventory.ItemStack.of(ItemStack.java:69)
[17:53:56 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149)
[17:53:56 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128)
[17:53:56 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.chests.ChestEntry.rollEntry(ChestEntry.java:37)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.chests.ChestContents$ChestRarity.rollLoot(ChestContents.java:187)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.chests.ChestContents.rollChestContents(ChestContents.java:159)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitAnything.fillChests(FitAnything.java:290)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitAnything.paste(FitAnything.java:199)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitSurfaceBuilding.scan(FitSurfaceBuilding.java:62)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitSurfaceBuilding.<init>(FitSurfaceBuilding.java:25)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.listeners.NewChunkLoadEvent.surfaceScanner(NewChunkLoadEvent.java:57)
[17:53:56 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.listeners.NewChunkLoadEvent.onChunkLoad(NewChunkLoadEvent.java:45)
[17:53:56 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor826.execute(Unknown Source)
[17:53:56 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:53:56 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[17:53:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:53:56 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:53:56 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[17:53:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[17:53:56 WARN]:        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:660)
[17:53:56 WARN]:        at ca.spottedleaf.moonrise.common.util.ChunkSystem.onChunkBorder(ChunkSystem.java:91)
[17:53:56 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1296)
[17:53:56 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1364)
[17:53:56 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1348)
[17:53:56 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1303)
[17:53:56 WARN]:        at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:341)
[17:53:56 WARN]:        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:741)
[17:53:56 WARN]:        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337)
[17:53:56 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1560)
[17:53:56 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542)
[17:53:56 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[17:53:56 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1664)
[17:53:56 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333)
[17:53:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[17:53:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by servicomcr** [comment]
[03:03:35 WARN]: [BetterStructures] Failed to correctly fill chests!
[03:03:35 WARN]: java.lang.IllegalArgumentException: BAMBOO_SAPLING isn't an item
[03:03:35 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[03:03:35 WARN]:        at org.bukkit.inventory.ItemStack.of(ItemStack.java:69)
[03:03:35 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149)
[03:03:35 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128)
[03:03:35 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.chests.ChestEntry.rollEntry(ChestEntry.java:37)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.chests.ChestContents$ChestRarity.rollLoot(ChestContents.java:187)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.chests.ChestContents.rollChestContents(ChestContents.java:159)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitAnything.fillChests(FitAnything.java:290)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitAnything.paste(FitAnything.java:199)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitAirBuilding.scan(FitAirBuilding.java:125)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.buildingfitter.FitAirBuilding.<init>(FitAirBuilding.java:26)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.listeners.NewChunkLoadEvent.skyScanner(NewChunkLoadEvent.java:80)
[03:03:35 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.listeners.NewChunkLoadEvent.onChunkLoad(NewChunkLoadEvent.java:48)
[03:03:35 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor802.execute(Unknown Source)
[03:03:35 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[03:03:35 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[03:03:35 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:03:35 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[03:03:35 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[03:03:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[03:03:35 WARN]:        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:660)
[03:03:35 WARN]:        at ca.spottedleaf.moonrise.common.util.ChunkSystem.onChunkBorder(ChunkSystem.java:91)
[03:03:35 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1296)
[03:03:35 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1364)
[03:03:35 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1348)
[03:03:35 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1303)
[03:03:35 WARN]:        at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:341)
[03:03:35 WARN]:        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:741)
[03:03:35 WARN]:        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337)
[03:03:35 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1560)
[03:03:35 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542)
[03:03:35 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[03:03:35 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501)
[03:03:35 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1623)
[03:03:35 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333)
[03:03:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[03:03:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
