### ISSUE TITLE
Using MC version 1.21.1 get huge error

### ISSUE THREAD

**Issue by omegartlx** [MagmaGuy/BetterStructures#48]
Hi im using the version 1.21.1 and every time i try to initialize or do anything related to the plugin i just get this massive error.

Could not pass event InventoryClickEvent to BetterStructures v1.7.2
java.lang.NoClassDefFoundError: com/magmaguy/elitemobs/config/ConfigurationEngine
        at BetterStructures.jar/com.magmaguy.betterstructures.config.DefaultConfig.toggleSetupDone(DefaultConfig.java:55) ~[BetterStructures.jar:?]
        at BetterStructures.jar/com.magmaguy.betterstructures.menus.BetterStructuresFirstTimeSetupMenu$4.onClick(BetterStructuresFirstTimeSetupMenu.java:89) ~[BetterStructures.jar:?]
        at BetterStructures.jar/com.magmaguy.betterstructures.magmacore.menus.AdvancedMenu.run(AdvancedMenu.java:36) ~[BetterStructures.jar:?]
        at BetterStructures.jar/com.magmaguy.betterstructures.magmacore.menus.AdvancedMenuHandler$AdvancedMenuListeners.onInventoryInteraction(AdvancedMenuHandler.java:29) ~[BetterStructures.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor401.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2314-501e7c5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3306) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1549) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1542) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1501) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1353) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2314-501e7c5]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.magmaguy.elitemobs.config.ConfigurationEngine
        ... 29 more

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
