### ISSUE TITLE
Could not pass event InventoryClickEvent to BetterStructures v1.7.2

### ISSUE THREAD

**Issue by Bozhidar-A** [MagmaGuy/BetterStructures#49]
All proceeds well until `/betterstructures initialize` as clicking the glass pane does nothing. The server logs are as follows:

> [05:48:19] [Server thread/ERROR] [Minecraft/]: Could not pass event InventoryClickEvent to BetterStructures v1.7.2
> mc-1  | org.bukkit.event.EventException: null
> mc-1  |         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[forge-1.20.2-48.1.0-0.2.3-universal.jar%23155!/:?] {re:classloading}
> mc-1  |         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.2-48.1.0-0.2.3-universal.jar%23155!/:?] {re:classloading}
> mc-1  |         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:590) ~[forge-1.20.2-48.1.0-0.2.3-universal.jar%23155!/:?] {re:classloading,re:mixin,re:mixin}
> mc-1  |         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:577) ~[forge-1.20.2-48.1.0-0.2.3-universal.jar%23155!/:?] {re:classloading,re:mixin,re:mixin}
> mc-1  |         at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:2512) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading}
> mc-1  |         at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading}
> mc-1  |         at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading}
> mc-1  |         at net.minecraft.network.protocol.PacketUtils.m_292130_(PacketUtils.java:24) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading}
> mc-1  |         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading}
> mc-1  |         at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading}
> mc-1  |         at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1004) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:160) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:987) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:981) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:955) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:871) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> mc-1  |         at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:267) ~[server-1.20.2-20230921.100330-srg.jar%23149!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> mc-1  |         at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
> mc-1  | Caused by: java.lang.NoClassDefFoundError: com/magmaguy/elitemobs/config/ConfigurationEngine
> mc-1  |         at com.magmaguy.betterstructures.config.DefaultConfig.toggleSetupDone(DefaultConfig.java:55) ~[?:?] {}
> mc-1  |         at com.magmaguy.betterstructures.menus.BetterStructuresFirstTimeSetupMenu$4.onClick(BetterStructuresFirstTimeSetupMenu.java:89) ~[?:?] {}
> mc-1  |         at com.magmaguy.betterstructures.magmacore.menus.AdvancedMenu.run(AdvancedMenu.java:36) ~[?:?] {}
> mc-1  |         at com.magmaguy.betterstructures.magmacore.menus.AdvancedMenuHandler$AdvancedMenuListeners.onInventoryInteraction(AdvancedMenuHandler.java:29) ~[?:?] {}
> mc-1  |         at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
> mc-1  |         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
> mc-1  |         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[forge-1.20.2-48.1.0-0.2.3-universal.jar%23155!/:?] {re:classloading}
> mc-1  |         ... 20 more
> mc-1  | Caused by: java.lang.ClassNotFoundException: com.magmaguy.elitemobs.config.ConfigurationEngine
> mc-1  |         at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187) ~[forge-1.20.2-48.1.0-0.2.3-universal.jar%23155!/:?] {re:classloading,re:mixin}
> mc-1  |         at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:139) ~[forge-1.20.2-48.1.0-0.2.3-universal.jar%23155!/:?] {re:classloading,re:mixin}
> mc-1  |         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
> mc-1  |         at com.magmaguy.betterstructures.config.DefaultConfig.toggleSetupDone(DefaultConfig.java:55) ~[?:?] {}
> mc-1  |         at com.magmaguy.betterstructures.menus.BetterStructuresFirstTimeSetupMenu$4.onClick(BetterStructuresFirstTimeSetupMenu.java:89) ~[?:?] {}
> mc-1  |         at com.magmaguy.betterstructures.magmacore.menus.AdvancedMenu.run(AdvancedMenu.java:36) ~[?:?] {}
> mc-1  |         at com.magmaguy.betterstructures.magmacore.menus.AdvancedMenuHandler$AdvancedMenuListeners.onInventoryInteraction(AdvancedMenuHandler.java:29) ~[?:?] {}
> mc-1  |         at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
> mc-1  |         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
> mc-1  |         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[forge-1.20.2-48.1.0-0.2.3-universal.jar%23155!/:?] {re:classloading}
> mc-1  |         ... 20 more

From this big wall of text the important thing seems to be `Caused by: java.lang.ClassNotFoundException: com.magmaguy.elitemobs.config.ConfigurationEngine`. 

Any help is appreciated!

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
