### ISSUE TITLE
Plugin not working on paper 1.21.3

### ISSUE THREAD

**Issue by ChunkyDuck8223** [MagmaGuy/BetterStructures#50]
Hello, the plugin seems to not generate plugin default files. My server is running Geyser, AxGraves, BackpackPlus, BetterChairs, Chunky, floodgate, HuskHomes, LagFixer, ViaBackwards, Viaversion, voicechat, worldguard, Worldedit (All up to date). Elite mobs also gave me a similar warning. I'm not sure what to do

**EliteMobs**
[17:42:26 WARN]: [EliteMobs] Incompatible Minecraft version detected! [3] Package: org.bukkit.craftbukkit version: 1.21.3-44-85bfdc0 (MC: 1.21.3) and attempted to get v1_21_ ! Report this to the developer.
[17:42:26 WARN]: [EliteMobs] Server version is null.

**BetterStructures**
[17:42:39 WARN]: [BetterStructures] Failed to read plugin files for generators ! This is very bad, warn the developer!
[17:42:39 WARN]: java.lang.ClassCastException: class org.bukkit.craftbukkit.block.CraftBiome cannot be cast to class java.lang.Enum (org.bukkit.craftbukkit.block.CraftBiome is in unnamed module of loader java.net.URLClassLoader @17d10166; java.lang.Enum is in module java.base of loader 'bootstrap')
[17:42:39 WARN]:        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4266)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.magmacore.config.CustomConfigFields.enumListToStringListConverter(CustomConfigFields.java:183)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.magmacore.config.CustomConfigFields.processEnumList(CustomConfigFields.java:157)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.config.generators.GeneratorConfigFields.processConfigFields(GeneratorConfigFields.java:76)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.magmacore.config.CustomConfig.initialize(CustomConfig.java:159)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.magmacore.config.CustomConfig.fileInitializer(CustomConfig.java:108)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.magmacore.config.CustomConfig.directoryCrawler(CustomConfig.java:94)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.magmacore.config.CustomConfig.<init>(CustomConfig.java:78)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.config.generators.GeneratorConfig.<init>(GeneratorConfig.java:13)
[17:42:39 WARN]:        at BetterStructures.jar//com.magmaguy.betterstructures.BetterStructures.onEnable(BetterStructures.java:54)
[17:42:39 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[17:42:39 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[17:42:39 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[17:42:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[17:42:39 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643)
[17:42:39 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592)
[17:42:39 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767)
[17:42:39 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529)
[17:42:39 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326)
[17:42:39 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233)
[17:42:39 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339)
[17:42:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1575)
[17:42:39 ERROR]: Error occurred while enabling BetterStructures v1.7.2 (Is it up to date?)
java.util.ConcurrentModificationException: null
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096) ~[?:?]
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050) ~[?:?]
        at BetterStructures.jar/com.magmaguy.betterstructures.magmacore.config.CustomConfig.fileInitializer(CustomConfig.java:103) ~[BetterStructures.jar:?]
        at BetterStructures.jar/com.magmaguy.betterstructures.magmacore.config.CustomConfig.directoryCrawler(CustomConfig.java:94) ~[BetterStructures.jar:?]
        at BetterStructures.jar/com.magmaguy.betterstructures.magmacore.config.CustomConfig.<init>(CustomConfig.java:78) ~[BetterStructures.jar:?]
        at BetterStructures.jar/com.magmaguy.betterstructures.config.generators.GeneratorConfig.<init>(GeneratorConfig.java:13) ~[BetterStructures.jar:?]
        at BetterStructures.jar/com.magmaguy.betterstructures.BetterStructures.onEnable(BetterStructures.java:54) ~[BetterStructures.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-44-85bfdc0]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]

**Comment by ShoyebOP** [comment]
Same for me😢

**Comment by wkurumi** [comment]
+1

**Comment by MagmaGuy** [comment]
## Semi-automated AI reply
Replying on behalf of MagmaGuy based on his instructions.

Closing this legacy ticket because it predates the current BetterStructures 2.x release series and concerns a much older generation of the plugin.

Please update to the current release, 2.7.0. If this issue or request still applies, please open a new ticket with the current plugin/server versions and up-to-date details.
