### ISSUE TITLE
error with plugin lootin v5.3

### ISSUE THREAD

**Issue by antonioscarpino** [MagmaGuy/BetterStructures#6]
Hello by charging BetteStructures with the V5.3 plugin Looting I get this error that I understand from my ignorance is due to some mistakes within the api of Bettestructures. Is there a way to solve the problem? Thank you in advance for the support.

****

[15:21:58] [Server thread/ERROR]: Error occurred while enabling Lootin v5.3 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event com.magmaguy.betterstructures.api.ChestFillEvent. Static getHandlerList method required!
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:683) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:616) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.github.sachin.lootin.Lootin.onEnable(Lootin.java:110) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3569-Spigot-450dcaa-ead719a]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by MagmaGuy** [comment]
This should be fixed now.
